#if !canImport(ObjectiveC)
import XCTest

extension JSONAPIAttributeOpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONAPIAttributeOpenAPITests = [
        ("test_8601DateStringAttribute", test_8601DateStringAttribute),
        ("test_8601DateStringAttribute_Sampleable", test_8601DateStringAttribute_Sampleable),
        ("test_Arrayttribute", test_Arrayttribute),
        ("test_BooleanAttribute", test_BooleanAttribute),
        ("test_DateDeferredAttribute", test_DateDeferredAttribute),
        ("test_DateDeferredAttribute_Sampleable", test_DateDeferredAttribute_Sampleable),
        ("test_DateNumberAttribute", test_DateNumberAttribute),
        ("test_DateNumberAttribute_Sampleable", test_DateNumberAttribute_Sampleable),
        ("test_DateStringAttribute", test_DateStringAttribute),
        ("test_DateStringAttribute_Sampleable", test_DateStringAttribute_Sampleable),
        ("test_DateTimeStringAttribute", test_DateTimeStringAttribute),
        ("test_DateTimeStringAttribute_Sampleable", test_DateTimeStringAttribute_Sampleable),
        ("test_EnumAttribute", test_EnumAttribute),
        ("test_FloatNumberAttribute", test_FloatNumberAttribute),
        ("test_IntegerAttribute", test_IntegerAttribute),
        ("test_NullableArrayAttribute", test_NullableArrayAttribute),
        ("test_NullableBooleanAttribute", test_NullableBooleanAttribute),
        ("test_NullableDateAttribute", test_NullableDateAttribute),
        ("test_NullableEnumAttribute", test_NullableEnumAttribute),
        ("test_NullableIntegerAttribute", test_NullableIntegerAttribute),
        ("test_NullableNumberAttribute", test_NullableNumberAttribute),
        ("test_NullableStringAttribute", test_NullableStringAttribute),
        ("test_NumberAttribute", test_NumberAttribute),
        ("test_OptionalArrayAttribute", test_OptionalArrayAttribute),
        ("test_OptionalBooleanAttribute", test_OptionalBooleanAttribute),
        ("test_OptionalDateAttribute", test_OptionalDateAttribute),
        ("test_OptionalEnumAttribute", test_OptionalEnumAttribute),
        ("test_OptionalIntegerAttribute", test_OptionalIntegerAttribute),
        ("test_OptionalNullableArrayAttribute", test_OptionalNullableArrayAttribute),
        ("test_OptionalNullableBooleanAttribute", test_OptionalNullableBooleanAttribute),
        ("test_OptionalNullableDateAttribute", test_OptionalNullableDateAttribute),
        ("test_OptionalNullableEnumAttribute", test_OptionalNullableEnumAttribute),
        ("test_OptionalNullableIntegerAttribute", test_OptionalNullableIntegerAttribute),
        ("test_OptionalNullableNumberAttribute", test_OptionalNullableNumberAttribute),
        ("test_OptionalNullableStringAttribute", test_OptionalNullableStringAttribute),
        ("test_OptionalNumberAttribute", test_OptionalNumberAttribute),
        ("test_OptionalStringAttribute", test_OptionalStringAttribute),
        ("test_StringAttribute", test_StringAttribute),
    ]
}

extension JSONAPIDocumentOpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONAPIDocumentOpenAPITests = [
        ("test_DocumentWithOneIncludeType", test_DocumentWithOneIncludeType),
        ("test_DocumentWithTwoIncludeTypes", test_DocumentWithTwoIncludeTypes),
        ("test_ManyResourceDocument", test_ManyResourceDocument),
        ("test_SingleResourceDocument", test_SingleResourceDocument),
    ]
}

extension JSONAPIEntityOpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONAPIEntityOpenAPITests = [
        ("test_AttributesAndRelationshipsEntity", test_AttributesAndRelationshipsEntity),
        ("test_AttributesEntity", test_AttributesEntity),
        ("test_EmptyEntity", test_EmptyEntity),
        ("test_RelationshipsEntity", test_RelationshipsEntity),
        ("test_UnidentifiedEmptyEntity", test_UnidentifiedEmptyEntity),
    ]
}

extension JSONAPIRelationshipsOpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONAPIRelationshipsOpenAPITests = [
        ("test_NullableToOne", test_NullableToOne),
        ("test_OptionalNullableToOne", test_OptionalNullableToOne),
        ("test_OptionalToMany", test_OptionalToMany),
        ("test_OptionalToOne", test_OptionalToOne),
        ("test_ToMany", test_ToMany),
        ("test_ToOne", test_ToOne),
    ]
}

extension JSONAPITransformedAttributeOpenAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONAPITransformedAttributeOpenAPITests = [
        ("test_8601DateStringAttribute", test_8601DateStringAttribute),
        ("test_8601DateStringAttribute_Sampleable", test_8601DateStringAttribute_Sampleable),
        ("test_Arrayttribute", test_Arrayttribute),
        ("test_BooleanAttribute", test_BooleanAttribute),
        ("test_DateDeferredAttribute", test_DateDeferredAttribute),
        ("test_DateDeferredAttribute_Sampleable", test_DateDeferredAttribute_Sampleable),
        ("test_DateNumberAttribute", test_DateNumberAttribute),
        ("test_DateNumberAttribute_Sampleable", test_DateNumberAttribute_Sampleable),
        ("test_DateStringAttribute", test_DateStringAttribute),
        ("test_DateStringAttribute_Sampleable", test_DateStringAttribute_Sampleable),
        ("test_DateTimeStringAttribute", test_DateTimeStringAttribute),
        ("test_DateTimeStringAttribute_Sampleable", test_DateTimeStringAttribute_Sampleable),
        ("test_EnumAttribute", test_EnumAttribute),
        ("test_FloatNumberAttribute", test_FloatNumberAttribute),
        ("test_IntegerAttribute", test_IntegerAttribute),
        ("test_NullableArrayAttribute", test_NullableArrayAttribute),
        ("test_NullableBooleanAttribute", test_NullableBooleanAttribute),
        ("test_NullableDateAttribute", test_NullableDateAttribute),
        ("test_NullableEnumAttribute", test_NullableEnumAttribute),
        ("test_NullableIntegerAttribute", test_NullableIntegerAttribute),
        ("test_NullableNumberAttribute", test_NullableNumberAttribute),
        ("test_NullableStringAttribute", test_NullableStringAttribute),
        ("test_NumberAttribute", test_NumberAttribute),
        ("test_OptionalArrayAttribute", test_OptionalArrayAttribute),
        ("test_OptionalBooleanAttribute", test_OptionalBooleanAttribute),
        ("test_OptionalDateAttribute", test_OptionalDateAttribute),
        ("test_OptionalEnumAttribute", test_OptionalEnumAttribute),
        ("test_OptionalIntegerAttribute", test_OptionalIntegerAttribute),
        ("test_OptionalNullableArrayAttribute", test_OptionalNullableArrayAttribute),
        ("test_OptionalNullableBooleanAttribute", test_OptionalNullableBooleanAttribute),
        ("test_OptionalNullableDateAttribute", test_OptionalNullableDateAttribute),
        ("test_OptionalNullableEnumAttribute", test_OptionalNullableEnumAttribute),
        ("test_OptionalNullableIntegerAttribute", test_OptionalNullableIntegerAttribute),
        ("test_OptionalNullableNumberAttribute", test_OptionalNullableNumberAttribute),
        ("test_OptionalNullableStringAttribute", test_OptionalNullableStringAttribute),
        ("test_OptionalNumberAttribute", test_OptionalNumberAttribute),
        ("test_OptionalStringAttribute", test_OptionalStringAttribute),
        ("test_StringAttribute", test_StringAttribute),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONAPIAttributeOpenAPITests.__allTests__JSONAPIAttributeOpenAPITests),
        testCase(JSONAPIDocumentOpenAPITests.__allTests__JSONAPIDocumentOpenAPITests),
        testCase(JSONAPIEntityOpenAPITests.__allTests__JSONAPIEntityOpenAPITests),
        testCase(JSONAPIRelationshipsOpenAPITests.__allTests__JSONAPIRelationshipsOpenAPITests),
        testCase(JSONAPITransformedAttributeOpenAPITests.__allTests__JSONAPITransformedAttributeOpenAPITests),
    ]
}
#endif
